### ISSUE TITLE
Failed to run injection

### ISSUE THREAD

**Issue by ow0x** [powercord-community/permission-viewer#15]
Hi,

```js
[Powercord:Injector] Failed to run injection "jockie-permissionViewer-user" TypeError: Cannot read property 'props' of undefined
    at VM1427 index.js:188
    at VM877 index.js:104
    at Array.forEach (<anonymous>)
    at Object._runInjections (VM877 index.js:102)
    at VM877 index.js:37
```

so after #13 got fixed and I am now up to date on all version fronts, whenever I try to right click on a user who don't have any role to view their pemissions with this plugin, this pops up on dev console. Is this intended? I'm not sure, so decided to open an issue.

**Comment by FifiTheBulldog** [comment]
I just submitted PR #16 to fix this by adding a fallback for determining where the Permissions menu item should be located.
