### ISSUE TITLE
Permission Viewer - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by 515ivan515** [powercord-community/permission-viewer#3]
github link sends to 404

**Comment by 21Joakim** [comment]
Which link?

**Comment by 515ivan515** [comment]
https://discordsource.com/plugin/permission-viewer/
The download at the bottom of the page redirects to:
https://github.com/powercord-community/permission-viewer/tree/master/jockie-permissionViewer
It should go to:
https://github.com/powercord-community/permission-viewer/

**Comment by 21Joakim** [comment]
Yeah, I am not responsible for that
